Move things around

diff --git a/chef-runner b/chef-runner
--- a/chef-runner
+++ b/chef-runner
@@ -14,22 +14,6 @@ abort(){
     exit 1
 }
 
-cookbook_name() {
-    file="metadata.rb"
-    test -f "$file" || abort "error: $file not found"
-    head -n1 "$file" | sed "s/^name/echo/" | sh
-}
-
-cookbook_path() {
-    for dir in "cookbooks" "vendor/cookbooks"; do
-        if test -d "$dir"; then
-            echo "$dir"
-            return
-        fi
-    done
-    abort "error: cookbook path not found"
-}
-
 parse_args() {
     while test "$#" -ne 0; do
         case "$1" in
@@ -44,7 +28,7 @@ parse_args() {
             -|[!-]*)
                 break ;;
             -*)
-                echo >&2 "error: invalid option '$1'"; exit 1 ;;
+                abort "error: invalid option '$1'" ;;
         esac
     done
 
@@ -61,6 +45,22 @@ parse_args() {
     else
         RUNLIST="$COOKBOOK_NAME::default"
     fi
+}
+
+cookbook_name() {
+    file="metadata.rb"
+    test -f "$file" || abort "error: $file not found"
+    head -n1 "$file" | sed "s/^name/echo/" | sh
+}
+
+cookbook_path() {
+    for dir in "cookbooks" "vendor/cookbooks"; do
+        if test -d "$dir"; then
+            echo "$dir"
+            return
+        fi
+    done
+    abort "error: cookbook path not found"
 }
 
 run_ssh() {
@@ -81,8 +81,8 @@ run_chef() {
 }
 
 HOST=
-FORMAT="minimal"
 RUNLIST=
+FORMAT="minimal"
 COOKBOOK_NAME=${COOKBOOK_NAME:-$(cookbook_name)}
 COOKBOOK_PATH=${COOKBOOK_PATH:-$(cookbook_path)}
 
