Fix: allow to pass no arg to script/coverage again

diff --git a/script/coverage b/script/coverage
--- a/script/coverage
+++ b/script/coverage
@@ -41,10 +41,12 @@ push_to_coveralls() {
 generate_cover_data $(go list ./...)
 show_cover_report func
 case "$1" in
+"")
+    ;;
 --html)
     show_cover_report html ;;
 --coveralls)
     push_to_coveralls ;;
 *)
-    echo >&2 "error: invalid option"; exit 1 ;;
+    echo >&2 "error: invalid option: $1"; exit 1 ;;
 esac
